### PR TITLE
CORE-9234: added a join table to allow templates to have nested attri…

### PR DESCRIPTION
**Pull request by slr71**
…butes

### CODE REVIEW

**Review by johnworth — APPROVED** [review]
👍 :shipit:

**Review by psarando — APPROVED** [review]
LGTM 👍 

Do we also want a `unique` parent <-> child constraint in `constraints/18_attr_attrs.sql`?

**Comment by slr71** [comment]
Adding a unique parent <-> child constraint sounds reasonable to me. I'll add it.

**Comment by slr71** [comment]
I made a slight change to the uniqueness constraint. For the time being, it's probably best not to allow a child attribute to have more than one parent attribute either. Instead of adding a unique index on the `parent_id` and `child_id` columns, I added a uniqueness constraint to the index on the `child_id` column.

**Comment by slr71** [comment]
Thanks for the reviews!

**Comment by ianmcorvidae** [comment]
I know this has already been merged since I was busy this morning, but do we want to allow the parent and child IDs to be the same ID (could be weird to deal with in code?), do we want to prevent it in code (maybe the most consistent with other stuff?), or should something like `CHECK (parent_id <> child-id)` be added to the table?

**Comment by slr71** [comment]
I'd planned to prevent that in code, but adding the check seems reasonable. I'll add that as well.

**Pull request merged**
