### PR TITLE
Add conversion to add quick launch and instant launches to the target_enum

### PR DESCRIPTION
**Pull request by johnworth**
I tested the conversion and the new enum values against unittest-dedb without issues.

### CODE REVIEW

**Review by slr71 — COMMENTED** [review]
It looks like the update to the `version` table is missing from `src/main/data/99_version.sql`. Other than that, everything looks good to me.

**Comment by johnworth** [comment]
I always forget that version table. Thanks!

**Review by psarando — APPROVED** [review]
LGTM 👍

**Comment by johnworth** [comment]
Thanks for the reviews!

**Pull request merged**
