### PR TITLE
CORE-9235: added the "Grouping" value type for attributes that are no…

### PR DESCRIPTION
**Pull request by slr71**
…t expected to contain values, but merely to be placeholders for grouping other attributes together

I'm going to merge this change immediately. Reviews are still welcome and desired.

### CODE REVIEW

**Review by yeea — APPROVED** [review]
:shipit:

**Comment by slr71** [comment]
Thanks for the review!

**Review by psarando — APPROVED** [review]
LGTM :shipit: 

I presume this is for grouping attributes like `geoLocationPlace`, `pointLongitude`, and `pointLatitude` under a group like `geoLocation`?

Good idea 👍

**Comment by slr71** [comment]
Thanks for the review!

Yep, that's what I had in mind. Thanks!

**Pull request merged**
